language: php

php:
   # - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    
before_script:
    - code_path=$(pwd)
    - export WP_DEVELOP_DIR=/tmp/wordpress/
    - mkdir -p $WP_DEVELOP_DIR
    - cd $WP_DEVELOP_DIR
 # Install CodeSniffer for WordPress Coding Standards checks.
    - git clone https://github.com/squizlabs/PHP_CodeSniffer.git php-codesniffer
# Install WordPress Coding Standards.
    - git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wordpress-coding-standards
# Hop into CodeSniffer directory.
    - cd php-codesniffer
# Set install path for WordPress Coding Standards
# @link https://github.com/squizlabs/PHP_CodeSniffer/blob/4237c2fc98cc838730b76ee9cee316f99286a2a7/CodeSniffer.php#L1941
    - scripts/phpcs --config-set installed_paths ../wordpress-coding-standards
# After CodeSniffer install you should refresh your path.
    - phpenv rehash
    - cd $code_path
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: 
    - cd $code_path
    - $WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./phpcs.xml --extensions=php
    - phpunit
